config/routes.rb
Rails.application.routes.draw do
  mount ShopifyApp::Engine, at: '/'

  post 'callback/:id', to: 'callback#search'

  resources :rates

  get 'retry', to: 'home#retry'

  namespace :admin do
    resources :shops, only: [:show]
  end

  root to: 'home#index'
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :shop

  has_many :conditions, dependent: :destroy
  has_many :product_specific_prices, dependent: :destroy

  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0, less_than: 999_999_999 }
  validates :price_weight_modifier, presence: true, numericality: { greater_than_or_equal_to: 0, less_than: 999_999_999 }
  validates :price_weight_modifier_starter, presence: true, numericality: { greater_than_or_equal_to: 0, less_than: 999_999_999 }
  validates :price_total_modifier, presence: true, numericality: { greater_than_or_equal_to: 0, less_than: 999_999_999 }
  validates :price_total_modifier_starter, presence: true, numericality: { greater_than_or_equal_to: 0, less_than: 999_999_999 }
  validates :min_price, numericality: { greater_than_or_equal_to: 0, less_than: 999_999_999 }, allow_nil: true
  validates :max_price, numericality: { greater_than_or_equal_to: 0, less_than: 999_999_999 }, allow_nil: true
  validates :min_grams, numericality: { greater_than_or_equal_to: 0, less_than: 999_999_999 }, allow_nil: true
  validates :max_grams, numericality: { greater_than_or_equal_to: 0, less_than: 999_999_999 }, allow_nil: true

  accepts_nested_attributes_for :conditions, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :product_specific_prices, allow_destroy: true, reject_if: :all_blank

  def limits
    {
      min_price: min_price,
      max_price: max_price,
      min_grams: min_grams,
      max_grams: max_grams,
    }.select { |_, v| v }
  end
end

app/controllers/rates_controller.rb
class RatesController < ShopifyApp::AuthenticatedController
  def index
    @rates = shop.rates.includes(:conditions, :product_specific_prices).order(:name)

    if @rates.empty?
      render('blank')
    else
      render('index')
    end
  end

  def show
    @rate = shop.rates.find(params[:id])
  end

  def new
    @rate = shop.rates.build
  end

  def update
    rate = shop.rates.find(params[:id])

    if rate.update_attributes(rate_params)
      redirect_to(rates_path)
    else
      redirect_to(rate_path(rate))
    end
  end

  def destroy
    rate = shop.rates.find(params[:id])

    if rate.destroy
      redirect_to(rates_path)
    else
      redirect_to(rate_path(rate))
    end
  end

  def create
    @rate = shop.rates.build(rate_params)

    if @rate.save
      redirect_to(rates_path)
    else
      render('new')
    end
  end

  private

  def rate_params
    params.require(:rate).permit(
      :name,
      :price,
      :price_weight_modifier,
      :price_weight_modifier_starter,
      :price_total_modifier,
      :price_total_modifier_starter,
      :description,
      :min_price,
      :max_price,
      :min_grams,
      :max_grams,
      :code,
      :notes,
      conditions_attributes: condition_params,
      product_specific_prices_attributes: product_specific_price_params
    )
  end

  def condition_params
    [:id, :field, :verb, :value, :all_items_must_match, :_destroy]
  end

  def product_specific_price_params
    [:id, :field, :verb, :value, :price, :_destroy]
  end
end

app/views/rates/_condition.html.erb
<div class="section-row" data-condition>
  <div class="section-cell">
    <a href="#" class="right" data-condition-destroy>
      <span class="icon ico-clear-bluegray"></span>
    </a>

    <%= f.hidden_field :_destroy, value: local_assigns.fetch(:destroyed, false) %>

    <%= f.label :field %>
    <div class="select-wrapper">
      <%=
        f.select :field,
          Matcher::FIELDS.map { |field| [t(field, scope: 'matcher.fields'), field] },
          { prompt: 'Field' },
          { class: 'select', data: { condition_field: true } }
      %>
    </div>

    <%= f.label :verb %>
    <div class="select-wrapper">
      <%=
        f.select :verb,
          Matcher::VERBS.map { |verb| [t(verb, scope: 'matcher.verbs'), verb] },
          { prompt: 'Verb' },
          { class: 'select' }
      %>
    </div>

    <%= f.label :value %>
    <%= f.text_field :value %>

    <div data-product-attributes style="display: none;">
      <%= f.radio_button :all_items_must_match, true %>
      <%= f.label :all_items_must_match_true, "All items in carts must match" %>

      <%= f.radio_button :all_items_must_match, false %>
      <%= f.label :all_items_must_match_false, "At least one item must match" %>
    </div>
  </div>
</div>

app/views/rates/_form.html.erb
<%= form_for(@rate) do |f| %>
  <div class="section">
    <div class="section-summary">
      <h1>Public Details</h1>
      <p>Information shown in the cart regarding this shipping rate.</p>
    </div>
    <div class="section-content">
      <div class="section-row">
        <div class="section-cell">
          <%= f.label :name %>
          <%= f.text_field :name, placeholder: 'Bike delivery' %>
          <%= f.label :description %>
          <%= f.text_area :description, placeholder: 'I offer personal bike delivery in my neighborhood.' %>
        </div>
      </div>
    </div>
  </div>

  <div class="section">
    <div class="section-summary">
      <h1>Advanced Settings</h1>
      <p>Optional settings for advanced users. Leave blank for default values.</p>
    </div>
    <div class="section-content">
      <div class="section-row">
        <div class="section-cell">
          <%= f.label :code, 'Code (optional, must be unique across all rates)' %>
          <%= f.text_field :code, placeholder: 'bike-delivery' %>
          <%= f.label :notes %>
          <%= f.text_area :notes, placeholder: 'Internal notes or description about this rate and what it is for.' %>
        </div>
      </div>
    </div>
  </div>

  <div class="section">
    <div class="section-summary">
      <h1>Price (<%= shop.currency %>)</h1>
      <p>Prices are in sub-units, i.e. cents, pennies, pence, etc.</p>
      <p>Total Price = Base price + (Price per gram * (grams - starting grams) + (Price per cent * (cents - starting cents) + extras per item</p>
    </div>
    <div class="section-content">
      <div class="section-row">
        <div class="section-cell">
          <%= f.label :price, 'Base Price (in cents, pennies, pence, etc.)' %>
          <%= f.text_field :price, placeholder: 0 %>
        </div>
      </div>
      <div class="section-row">
        <div class="section-cell">
          <%= f.label :price_weight_modifier, 'Price per gram' %>
          <%= f.text_field :price_weight_modifier, placeholder: 0 %>
        </div>
        <div class="section-cell">
          <%= f.label :price_weight_modifier, 'Starting after X gram(s)...' %>
          <%= f.text_field :price_weight_modifier_starter, placeholder: 0 %>
        </div>
      </div>
      <div class="section-row">
        <div class="section-cell">
          <%= f.label :price_total_modifier, 'Price per cent' %>
          <%= f.text_field :price_total_modifier, placeholder: 0 %>
        </div>
        <div class="section-cell">
          <%= f.label :price_total_modifier, 'Starting after X cent(s)...' %>
          <%= f.text_field :price_total_modifier_starter, placeholder: 0 %>
        </div>
      </div>
    </div>
  </div>

  <div class="section">
    <div class="section-summary">
      <h1>Limits</h1>
      <p>Restrict availability of rates through price and weight.</p>
    </div>
    <div class="section-content">
      <div class="section-row">
        <div class="section-cell">
          <%= f.label :min_grams %>
          <%= f.text_field :min_grams %>
        </div>
        <div class="section-cell">
          <%= f.label :max_grams %>
          <%= f.text_field :max_grams %>
        </div>
      </div>
      <div class="section-row">
        <div class="section-cell">
          <%= f.label :min_price %>
          <%= f.text_field :min_price %>
        </div>
        <div class="section-cell">
          <%= f.label :max_price %>
          <%= f.text_field :max_price %>
        </div>
      </div>
    </div>
  </div>

  <div class="section">
    <div class="section-summary">
      <h1>Additional cost per item</h1>
      <p>
        Add per-product price to rates. They're added once per item matching criterias.
      </p>
      <p>
        <button class="btn primary" data-product_specific_price-add>
          Add an extra
        </button>

        <div style="display: none;" data-product_specific_price-template>
          <%= f.fields_for :product_specific_prices, ProductSpecificPrice.new do |ff| %>
            <%= render 'product_specific_price', f: ff, destroyed: true, disabled: true %>
          <% end %>
        </div>
      <p>
    </div>
    <div class="section-content" data-product_specific_price-list>
      <% @rate.product_specific_prices.each do |product_specific_price| %>
        <%= f.fields_for :product_specific_prices, product_specific_price do |ff| %>
          <%= render 'product_specific_price', f: ff %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="section">
    <div class="section-summary">
      <h1>Filters</h1>
      <p>
        Filters decide whether or not a rate is available.
        Countries and provinces use the <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2">ISO 3166-1 alpha-2</a> standard code.
        Filters are additive and compounded as ANDs. If you want ORs, use the | character to separate values.
        <a href="https://christianblais.github.io/Parcelify/" target="_blank">See our help for more details</a>.
      </p>
      <p>
        <button class="btn primary" data-condition-add>
          Add a filter
        </button>

        <div style="display: none;" data-condition-template>
          <%= f.fields_for :conditions, Condition.new do |ff| %>
            <%= render 'condition', f: ff, destroyed: true, disabled: true %>
          <% end %>
        </div>
      <p>
    </div>
    <div class="section-content" data-condition-list>
      <% @rate.conditions.each do |condition| %>
        <%= f.fields_for :conditions, condition do |ff| %>
          <%= render 'condition', f: ff %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

<% content_for :shopify_app_javascript do %>
  ShopifyApp.Bar.initialize({
    title: "<%= @rate.persisted? ? @rate.name : 'New' %>",
    breadcrumb: { label: "Shipping rates", href: "<%= rates_path %>", target: 'app', loading: false },
    buttons: {
      primary: { label: "Save", callback: function() {
        $('form').submit()
      }},
      secondary: [
        {
          label: "Help", callback: function() {
            window.open("https://christianblais.github.io/Parcelify/", '_blank')
          }
        },
        {
          label: "Cancel", callback: function() {
            window.location = "<%= rates_path %>"
          }
        }
      ]
    }
  });

  <% if @rate.errors.any? %>
    ShopifyApp.flashError('Oops, something went wrong!');
  <% end %>
<% end %>

app/views/rates/_product_specific_price.html.erb
<div class="section-row" data-product_specific_price>
  <div class="section-cell">
    <a href="#" class="right" data-product_specific_price-destroy>
      <span class="icon ico-clear-bluegray"></span>
    </a>

    <%= f.hidden_field :_destroy, value: local_assigns.fetch(:destroyed, false) %>

    <%= f.label :field %>
    <div class="select-wrapper">
      <%=
        f.select :field,
          Matcher::PRODUCT_FIELDS.map { |field| [t(field, scope: 'matcher.fields'), field] },
          { prompt: 'Field' },
          { class: 'select' }
      %>
    </div>

    <%= f.label :verb %>
    <div class="select-wrapper">
      <%=
        f.select :verb,
          Matcher::VERBS.map { |verb| [t(verb, scope: 'matcher.verbs'), verb] },
          { prompt: 'Verb' },
          { class: 'select' }
      %>
    </div>

    <%= f.label :value %>
    <%= f.text_field :value %>

    <%= f.label :price, 'Price to add' %>
    <%= f.text_field :price %>
  </div>
</div>

app/views/rates/blank.html.erb
<div class="section">
  <div class="section-content">
    <div class="section-row">
      <div class="section-cell">
        <label>Welcome to Parcelify!</label>
        <p>
          Parcelify let you create simple yet powerful shipping rates based on address fields, products, total weight or price. Whether you'd like to create a "5$ Bike delivery" shipping rates for your neighbors, a "Free hand delivery" for your coworkers or an expensive 25$ "Plane delivery" for that remote region in your country, we've got your back. Oh! you want that rate only for orders above $100? You can do that, too!
        </p>
        <p>
          You can find all the help required on <a href="https://christianblais.github.io/Parcelify/" target="_blank">our Github page</a>.
        </p>
        <p>
          Ready to start? Go ahead, and add a new shipping rate!
        </p>
      </div>
    </div>
  </div>
</div>

<% content_for :shopify_app_javascript do %>
  ShopifyApp.Bar.initialize({
    title: 'Welcome',
    buttons: {
      primary: { label: "New shipping rate", callback: function() {
        window.location = "<%= new_rate_path %>"
      }}
    }
  });
<% end %>

app/views/rates/index.html.erb
<div class="box notice">
  <i class="ico-notice"></i>
  Do you like Parcelify? Please help me and other merchants by <a href="https://apps.shopify.com/parcelify" target="_blank">writing a review on the app store</a>. Your reviews help others know what to expect when they’re looking for the service we offer and help me keep this all for free. Thank you!
</div>

<div class="section">
  <div class="section-summary">
    <h1>Shipping Rates</h1>
    <p>These are the shipping rates you created.</p>
  </div>

  <div class="section-content">
    <% @rates.each do |rate| %>
      <div class="section-row">
        <div class="section-cell">

          <div class="cell-container">
            <div class="cell-column">
              <h1 style="font-size: 1.5em; color: #31373d">
                <%= rate.name %>
                <span class="tag lightgray">
                  <%=
                    number_to_currency(
                      rate.price / 100.0,
                      unit: shop.currency,
                      format: "%n %u"
                    )
                  %>

                  <% unless rate.price_weight_modifier.zero? %>
                    <%= " + " %>
                    <%=
                      number_to_currency(
                        rate.price_weight_modifier / 100.0,
                        format: "%n"
                      )
                    %>
                    <%= " per gram" %>

                    <% unless rate.price_weight_modifier_starter.zero? %>
                      <%= " after " %>
                      <%= pluralize(rate.price_weight_modifier_starter, "gram") %>
                    <% end %>
                  <% end %>

                  <% unless rate.price_total_modifier.zero? %>
                    <%= " + " %>
                    <%=
                      number_to_percentage(
                        rate.price_total_modifier * 100,
                        precision: 2,
                        strip_insignificant_zeros: true
                      )
                    %>
                    <%= " of cart total price" %>

                    <% unless rate.price_total_modifier_starter.zero? %>
                      <%= " after " %>
                      <%=
                        number_to_currency(
                          rate.price_total_modifier_starter / 100.0,
                          format: "%n"
                        )
                      %>
                    <% end %>
                  <% end %>
                </span>
              </h1>

              <ul class="segmented right">
                <li><%= link_to 'Edit', rate_path(rate), class: %w(btn default btn-slim) %></li>
                <li><%= link_to 'Delete', rate_path(rate), method: :delete, class: %w(btn destroy btn-slim), data: { confirm: "Delete \"#{rate.name}\"?" } %></li>
              </ul>
            </div>
          </div>

          <% if rate.notes.present? %>
            <div class="cell-container">
              <div class="cell-column">
                <h1><%= rate.notes %></h1>
              </div>
            </div>
          <% end %>

          <% if rate.limits.any? %>
            <div class="cell-container">
              <div class="cell-column">
                <h1>This rate is only valid for orders within those limits:</h1>
                <ul>
                  <% if rate.min_price.present? %>
                    <li>
                      <%= Rate.human_attribute_name(:min_price) %>:
                      <%=
                        number_to_currency(
                          rate.min_price / 100.0,
                          unit: shop.currency,
                          format: "%n %u"
                        )
                      %>
                    </li>
                  <% end %>

                  <% if rate.max_price.present? %>
                    <li>
                      <%= Rate.human_attribute_name(:max_price) %>:
                      <%=
                        number_to_currency(
                          rate.max_price / 100.0,
                          unit: shop.currency,
                          format: "%n %u"
                        )
                      %>
                    </li>
                  <% end %>

                  <% if rate.min_grams.present? %>
                    <li>
                      <%= Rate.human_attribute_name(:min_grams) %>:
                      <%= number_with_delimiter(rate.min_grams) %> grams
                    </li>
                  <% end %>

                  <% if rate.max_grams.present? %>
                    <li>
                      <%= Rate.human_attribute_name(:max_grams) %>:
                      <%= number_with_delimiter(rate.max_grams) %> grams
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
          <% end %>

          <% if rate.product_specific_prices.any? %>
            <div class="cell-container">
              <div class="cell-column">
                <h1>Additional costs will be applied;</h1>
                <ul>
                  <% rate.product_specific_prices.each do |product_specific_price| %>
                    <li>
                      <%=
                        number_to_currency(
                          product_specific_price.price / 100.0,
                          unit: shop.currency,
                          format: "%n %u"
                        )
                      %>
                      <%= "when an item has a" %>
                      <%= t(product_specific_price.field, scope: 'matcher.fields').downcase %>
                      <%= "that" %>
                      <%= t(product_specific_price.verb, scope: 'matcher.actions').downcase %>
                      <%= truncate(product_specific_price.value) %></td>
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
          <% end %>

          <% if rate.conditions.any? %>
            <div class="cell-container">
              <div class="cell-column">
                <h1>This rate is only valid when all the following conditions are met;</h1>
                <ul>
                  <% rate.conditions.each do |condition| %>
                    <li>
                      <% if Matcher::PRODUCT_FIELDS.include?(condition.field) %>
                        <% if condition.all_items_must_match? %>
                          <%= "all" %>
                        <% else %>
                          <%= "at least one" %>
                        <% end %>
                        <%= t(condition.field, scope: 'matcher.fields').downcase.pluralize %>
                      <% else %>
                        <%= "the destination" %>
                        <%= t(condition.field, scope: 'matcher.fields').downcase %>
                      <% end %>
                      <%= t(condition.verb, scope: 'matcher.actions').downcase %>
                      <%= truncate(condition.value) %>
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
          <% end %>
        </div>
      </div>

    <% end %>
  </div>
</div>

<% content_for :shopify_app_javascript do %>
  ShopifyApp.Bar.initialize({
    title: 'Shipping Rates',
    buttons: {
      primary: { label: "New shipping rate", callback: function() {
        window.location = "<%= new_rate_path %>"
      }},
      secondary: [{
        label: "Troubleshoot", callback: function() {
          ShopifyApp.Modal.confirm(
            {
              title: "Having problems?",
              message: "Rates are not showing up? Having problems deleting / reinstalling the app? You can take a look at our documentation, or alternatively we can try to sync back Parcelify with Shopify. Just click here, sit back, relax, and wait. You won't loose any progress.",
              okButton: "Yes, sync with Shopify",
              cancelButton: "Cancel",
              style: "danger"
            }, function(result) {
              if (result) {
                window.location = "<%= retry_path %>"
              }
            }
          );
        }
      },
      {
        label: "Help", callback: function() {
          window.open("https://christianblais.github.io/Parcelify/", '_blank')
        }
      }]
    }
  });
<% end %>

app/views/rates/new.html.erb
<%= render 'form' %>

app/views/rates/show.html.erb
<%= render 'form' %>